const CREATE_ORDER = "oder:CREATE_ORDER";
const GET_ORDERS = 'order:GET_ALL_ORDERS';
const GET_LOGGED_USER_ORDERS = 'order:GET_LOGGED_USER_ORDER';
const UPDATE_ORDER = 'order:UPDATE_ORDER';

module.exports = {
  CREATE_ORDER,
  GET_ORDERS,
  GET_LOGGED_USER_ORDERS,
  UPDATE_ORDER
};
