const CREATE_SUBCATEGORY = 'subcategory:CREATE_SUBCATEGORY';
const UPDATE_SUBCATEGORY = 'subcategory:UPDATE_SUBCATEGORY';
const GET_ALL_SUBCATEGORIES = 'subcategory:GET_ALL_SUBCATEGORIES';
const GET_SPECIFIC_SUBCATEGORY = 'subcategory:GET_SPECIFIC_SUBCATEGORY';
const DELETE_SUBCATEGORY ='subcategory:DELETE_SUBCATEGORY';

module.exports = {
  CREATE_SUBCATEGORY,
  UPDATE_SUBCATEGORY,
  GET_ALL_SUBCATEGORIES,
  GET_SPECIFIC_SUBCATEGORY,
  DELETE_SUBCATEGORY
};