const CREATE_BRAND = "brand:CREATE_BRAND";
const UPDATE_BRAND = "brand:UPDATE_BRAND";
const GET_ALL_BRANDS = "brand:GET_ALL_BRANDS";
const GET_SPECIFIC_BRAND = "brand:GET_SPECIFIC_BRAND";
const DELETE_BRAND = "brand:DELETE_BRAND";

module.exports = {
  CREATE_BRAND,
  UPDATE_BRAND,
  GET_ALL_BRANDS,
  GET_SPECIFIC_BRAND,
  DELETE_BRAND,
};
