const CREATE_CATEGORY = 'category:CREATE_CATEGORY';
const UPDATE_CATEGORY = 'category:UPDATE_CATEGORY';
const GET_ALL_CATEGORIES = 'category:GET_ALL_CATEGORIES';
const GET_SPECIFIC_CATEGORY = 'category:GET_SPECIFIC_CATEGORY';
const DELETE_CATEGORY = 'category:DELETE_CATEGORY';

module.exports = {
  CREATE_CATEGORY,
  UPDATE_CATEGORY,
  GET_ALL_CATEGORIES,
  GET_SPECIFIC_CATEGORY,
  DELETE_CATEGORY
};