const CREATE_USER = 'user:CREATE_USER';
const UPDATE_USER = 'user:UPDATE_USER';
const GET_ALL_USERS = 'user:GET_ALL_USERS';
const GET_SPECIFIC_USER = 'user:GET_SPECIFIC_USER';
const DELETE_USER = 'user:DELETE_USER'
const GET_LOGGED_USER = 'user:GET_LOGGED_USER';
const UPDATE_LOGGED_USER = 'user:UPDATE_LOGGED_USER';
const DELETE_LOGGED_USER = 'user:DELETE_LOGGED_USER';

module.exports = {
  CREATE_USER,
  UPDATE_USER,
  GET_ALL_USERS,
  GET_SPECIFIC_USER,
  DELETE_USER,
  GET_LOGGED_USER,
  UPDATE_LOGGED_USER,
  DELETE_LOGGED_USER
};