const ADD_USER_ADDRESS = "address:ADD_USER_ADDRESS";
const GET_USER_ADDRESSES = "address:GET_USER_ADDRESSES";
const DELETE_USER_ADDRESS = "address:DELETE_USER_ADDRESS";

module.exports = {
  ADD_USER_ADDRESS,
  GET_USER_ADDRESSES,
  DELETE_USER_ADDRESS,
};
