const CREATE_PRODUCT = 'product:CREATE_PRODUCT';
const UPDATE_PRODUCT = 'product:UPDATE_PRODUCT';
const GET_ALL_PRODUCTS = 'product:GET_ALL_PRODUCTS';
const GET_SPECIFIC_PRODUCT = 'product:GET_SPECIFIC_PRODUCT';
const DELETE_PRODUCT = 'product:DELETE_PRODUCT';

module.exports = {
  CREATE_PRODUCT,
  UPDATE_PRODUCT,
  GET_ALL_PRODUCTS,
  GET_SPECIFIC_PRODUCT,
  DELETE_PRODUCT
};