const ADD_PRODUCT_TO_WISHLIST = 'wishlist:ADD_PRODUCT_TO_WISHLIST';
const DELETE_PRODUCT_FROM_WISHLIST = "wishlist:DELETE_PRODUCT_TO_WISHLIST";
const GET_PRODUCTS_IN_WISHLIST = "wishlist:GET_PRODUCTS_IN_WISHLIST";

module.exports = {
  ADD_PRODUCT_TO_WISHLIST,
  DELETE_PRODUCT_FROM_WISHLIST,
  GET_PRODUCTS_IN_WISHLIST,
};