const CREATE_NEW_COUPON = "coupon:CREATE_NEW_COUPON";
const DELETE_COUPON = "coupon:DELETE_COUPON";
const UPDATE_COUPON = "coupon:UPDATE_COUPON";
const GET_ALL_COUPONS = "coupon:GET_ALL_COUPONS";
const GET_SPECIFIC_COUPON = "coupon:GET_SPECIFIC_COUPON";

module.exports = {
  CREATE_NEW_COUPON,
  DELETE_COUPON,
  UPDATE_COUPON,
  GET_ALL_COUPONS,
  GET_SPECIFIC_COUPON,
};
