const ADD_PRODUCT_TO_CART = "cart:ADD_PRODUCT_TO_CART";
const GET_CART = "cart:GET_ALL_CART";
const UPDATE_ITEM_QUANTITY = 'cart:UPDATE_ITEM_QUANTITY';
const REMOVE_ITEM_FORM_CART = "cart:REMOVE_ITEM_FROM_CART";
const CLEAR_CART = "cart:CLEAR_CART";
const APPLY_COUPON = 'cart:APPLY_COUPON';

module.exports = {
  ADD_PRODUCT_TO_CART,
  GET_CART,
  REMOVE_ITEM_FORM_CART,
  CLEAR_CART,
  UPDATE_ITEM_QUANTITY,
  APPLY_COUPON,
};
